### ISSUE TITLE
Change WebkitMovementX --> movementX

### ISSUE THREAD

**Issue by idoivri** [bevanhunt/meteor-leaflet-demo#25]
Hi,

I'm getting messages about the deprecation of WebkitMovementX, like so:
'webkitMovementX' is deprecated. Please use 'movementX' instead.

This is happening on Chrome, version 45.0.2454.101 (64-bit).

I'm just noting this here as an FYI, as everything seems to be working and I might clone and submit a pull request later.

**Comment by bevanhunt** [comment]
Thanks for the report - the Leaflet project closed the issue - here is the link - https://github.com/Leaflet/Leaflet/issues/3943
