### ISSUE TITLE
Map does not show on Android

### ISSUE THREAD

**Issue by sailorsenergy** [bevanhunt/meteor-leaflet-demo#9]
Using Meteor 1.1.0.2, `meteor run android` produced the following with no map shown. Any ideas on how to fix it?
![screenshot from 2015-06-27 18 39 14](https://cloud.githubusercontent.com/assets/7704035/8393400/f9910e16-1cfc-11e5-9905-32941433a5cf.png)

**Comment by bevanhunt** [comment]
Hmm - I can repo it - but don't know why. I have no idea how to debug on this platform and as such I am not going to look into it. I will take a PR if you get it working. Cheers and good luck.

**Comment by bevanhunt** [comment]
Close - working on a PR right now https://github.com/bevanhunt/meteor-leaflet-demo/pull/10
